# Generated by Django 6.0.7 on 2026-08-18 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.JSONField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'datos_personales',
            },
        ),
        migrations.CreateModel(
            name='EquiposDeRefrigeracion',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=17, null=True)),
            ],
            options={
                'db_table': 'equipos_de_refrigeracion',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('tipo_insumo', models.CharField(max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=2, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_entrega', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('localizacion', models.CharField(choices=[('mostrador', 'Mostrador'), ('pedido', 'Bajo pedido')], default='mostrador', max_length=20)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero'), ('cocinero', 'Cocinero/Pastelero'), ('ayudante', 'Ayudante')], default='ayudante', max_length=20)),
                ('estado', models.CharField(blank=True, default='activo', max_length=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('datos_personales', models.OneToOneField(blank=True, db_column='id_datos_personales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasteleria_app.datospersonales')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteInsumo',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.insumos')),
            ],
            options={
                'db_table': 'lotes_insumos',
                'ordering': ['fecha_caducidad', 'id_lote'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('id_encargado', models.ForeignKey(db_column='id_encargado', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.equiposderefrigeracion')),
            ],
            options={
                'db_table': 'mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('adelanto', 'Adelanto'), ('pago_final', 'Pago final'), ('otro_ingreso', 'Otro ingreso'), ('egreso', 'Egreso')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pasteleria_app.caja')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasteleria_app.pedidos')),
            ],
            options={
                'db_table': 'movimientos_caja',
            },
        ),
        migrations.CreateModel(
            name='ProductoMostrador',
            fields=[
                ('id_producto_mostrador', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasteleria_app.pedidos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'producto_mostrador',
            },
        ),
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id_producto_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(default='almacen', max_length=20)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasteleria_app.pedidos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'producto_almacen',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.insumos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.pedidos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket', models.CharField(max_length=50, unique=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.pedidos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.productos')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='ProductoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.insumos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'producto_insumos',
                'unique_together': {('id_producto', 'id_insumo')},
            },
        ),
    ]
