# Generated by Django 6.0.7 on 2026-07-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.JSONField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'datos_personales',
            },
        ),
        migrations.CreateModel(
            name='EquiposDeRefrigeracion',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=17, null=True)),
            ],
            options={
                'db_table': 'equipos_de_refrigeracion',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('tipo_insumo', models.CharField(max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=2, null=True)),
                ('cantidad', models.JSONField()),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_entrega', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('total', models.JSONField()),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.JSONField()),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pasteleria_app.datospersonales')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=8)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProductoInsumos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_producto', 'id_insumo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.insumos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'producto_insumos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.JSONField()),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.insumos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.productos')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('total', models.JSONField()),
                ('ticket', models.CharField(max_length=50, unique=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.pedidos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.usuarios')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.JSONField()),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.productos')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('proximo_mantenimiento', models.JSONField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.equiposderefrigeracion')),
                ('id_encargado', models.ForeignKey(db_column='id_encargado', on_delete=django.db.models.deletion.DO_NOTHING, to='pasteleria_app.usuarios')),
            ],
            options={
                'db_table': 'mantenimientos',
            },
        ),
    ]
