# Generated by Django 6.0.7 on 2026-08-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_cajas_activas', models.PositiveIntegerField(default=1)),
                ('tiempo_maximo_minutos', models.PositiveIntegerField(default=120)),
            ],
            options={
                'db_table': 'configuracion_caja',
            },
        ),
    ]
