# Generated by Django 6.0.7 on 2026-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria_app', '0002_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero'), ('cocinero', 'Cocinero/Pastelero'), ('ayudante', 'Ayudante')], default='ayudante', max_length=20),
        ),
    ]
