# Generated by Django 6.0.7 on 2026-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria_app', '0002_configuracioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('bajo', 'Stock bajo'), ('agotado', 'Agotado')], default='disponible', editable=False, max_length=10),
        ),
    ]
