# Generated by Django 6.0.7 on 2026-08-19 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria_app', '0004_remove_caja_fecha_apertura_alter_caja_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
