# Generated by Django 6.0.7 on 2026-09-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria_app', '0005_caja_fecha_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.productos'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.productos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.productos'),
        ),
        migrations.AlterField(
            model_name='productoinsumos',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='pasteleria_app.productos'),
        ),
    ]
